spring.application.name=kafka-streams-cogroup-app-test
spring.kafka.bootstrap-servers=localhost:9092

# Kafka Streams configuration for testing
spring.kafka.streams.application-id=${spring.application.name}
spring.kafka.streams.properties.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.properties.default.value.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.properties.commit.interval.ms=1000
